apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytws
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mytws
  template:
    metadata:
      name: mytws
      labels:
        app: mytws
    spec:
      containers:
      - name : tws
        image: myapp
        imagePullPolicy: Never
        ports:
        - containerPort: 9092
          protocol: TCP
        env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: myapp
              key: HOST
        - name: TG_AP
          valueFrom:
            secretKeyRef:
              name: myapp
              key: TG_AP
