apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytws
  template:
    metadata:
      name: mytws
      labels:
        app: mytws
    spec:
      containers:
      - name : tws
        image: myapp
        imagePullPolicy: Never
        env:
        - name: HOST
          value: "kafka.kafka-ca1"
